### ISSUE TITLE
Should notify user when want to add more subreddits to a multireddit than possible

### ISSUE THREAD

**Issue by hirenshah** [blzsaa/reddit-custom-feed-bulk-editor#80]
Using http://multireddit-editor.vercel.app after navigating between pages, Save stops working.

**Comment by blzsaa** [comment]
What do you exactly mean by navigating between pages?
Could you please write down the necessary steps to reproduce a Bug.

**Comment by hirenshah** [comment]
I think I've figured it out. There is a 100 subreddit limit and if the changes you are saving will exceed the that limit, nothing happens.

Since there is no error message or anything, there was no way for me to know why it wasn't saving.
